name: fortune_wheel
description: "A highly customizable spinning fortune wheel widget for Flutter with advanced animations and backend integration support."
version: 0.1.0
homepage: https://github.com/AbdurahmanAlmehdi/fortune_wheel

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  curved_text: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
